---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: aspnetcore
  namespace: default
  labels:
    app: aspnetcore
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aspnetcore
  template:
    metadata:
      labels:
        app: aspnetcore
    spec:
      containers:
      - name: aspnetcore
        image: "aliashraf786/testproject:latest"
        ports:
          - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: aspnetcore
  namespace: default
spec:
  selector:
    app: aspnetcore
  type: LoadBalancer
  ports:
  - name: http
    targetPort: 3000
    port: 80